angular.module('umbraco').controller('KeyValueEditorDialogController', function($scope) {

  var vm = this
  vm.submit = submit
  vm.close = close

  var randomString = function(length) {
    var chars = '0123456789abcdefghijklmnopqrstuvwxyz'
    var result = ''
    for (var i = length; i > 0; --i) result += chars[Math.round(Math.random() * (chars.length - 1))]
    return result
  }

  if (!$scope.model.dialogData.key) {
    if ($scope.model.dialogData.config.autoGenerateKey) {
      $scope.model.dialogData.key = randomString($scope.model.dialogData.config.autoGeneratedKeyLength)
    }
    else {
      $scope.model.dialogData.key = null
    }
  }

  if (!$scope.model.dialogData.value) {
    $scope.model.dialogData.value = null
  }

  if (!$scope.model.dialogData.description) {
    $scope.model.dialogData.description = null
  }

  function submit() {
    if($scope.model.submit) {
      $scope.model.submit($scope.model.dialogData)
    }
  }

  function close() {
    if($scope.model.close) {
      $scope.model.close()
    }
  }
})